version: "3.3"
services:
  user_service:
    build: ./user_service
    ports:
      - 8008:8008
  torrent_service:
    build: ./torrent_service
    ports:
      - 8007:8007
  search_service:
    build: ./search_service
    ports:
      - 8006:8006
  comment_service:
    build: ./comment_service
    ports:
      - 8003:8003
  file_service:
    build: ./file_service
    ports:
      - 8004:8004
  rating_service:
    build: ./rating_service
    ports:
      - 8005:8005
  admin_service:
    build: ./admin_service
    ports:
      - 8000:8000
  auth_service:
    build: ./auth_service
    ports:
      - 8001:8001
  chatroom_service:
    build: ./chatroom_service
    ports:
      - 8002:8002
